### PR TITLE
Maintain aspect ratio on resize

### PR DESCRIPTION
**Pull request by arj03**
This is probably not meant to be merge but instead more meant as a discussion.

When I started using this library I thought resize would maintain aspect ratio and that width and height meant the max-width and max-height of the image. But it seems that the way it behaves now is more like, if you specify a width and height smaller than the image, then you will just a sort of zoomed version of the middle of the image with this width/height.

Secondly I snucked in a small change because I noticed that the callback was triggered twice, once, onload and another time as complete.

### CODE REVIEW

**Comment by christianbundy** [comment]
> This is probably not meant to be merge but instead more meant as a discussion.

Do you know who the other stakeholders on this are? I don't use ssb-blob-files, so I'm probably not the right person to review and merge, but I'd love to help move this forward.

**Comment by christianbundy** [comment]
Oops clicked the wrong button. :grimacing:

**Comment by arj03** [comment]
[It](https://github.com/ssbc/ssb-blob-files/network/dependents?package_id=UGFja2FnZS0xODU5MzI5Mjc%3D) seems as if this is used in patchwork and patchbay and @regular seems to be using this. The question is if they are using this feature or not.

**Comment by arj03** [comment]
@mixmix is probably the right person to ask what the feature is for in its current form.

**Comment by arj03** [comment]
Lastly I'm using this branch of the library in ssb-browser-demo.

**Comment by christianbundy** [comment]
Oh, I guess I'm a stakeholder then. :sweat_smile: 

I think this is way more reasonable than a zoom and crop on the center of the image, the only thing I'd love would be tests on the resize info. Even just making and testing a resize function that only works on the dimensions, like:

```javascript
function resizeDimensions (width, height) {
  // [secret sauce goes here]
  return [offsetX, offsetY, finalWidth, finalHeight]
}

const dimensions = resizeDimensions(width, height)
```

Test code:

```javascript
t.deepEqual(dimensions, [0, 0, 10, 10])
```

Production:

```javascript
ctx.drawImage(...dimensions)
```

**Comment by arj03** [comment]
Yeah that would be a good idea. But first I would like to know if I can just rip out the old functionality or if it was there on purpose :)

**Review by christianbundy — APPROVED** [review]
Well, in case the old behavior is *not* important to keep, I've pushed some tests to ensure backward-compat. This change is a :+1: from me, but I think it's wise to check in with @mixmix before merging.

**Comment by arj03** [comment]
Ha, you are on 🔥 @christianbundy. Thanks for the test :-)

**Comment by arj03** [comment]
I looked through all the projects that seems to using this library, but most of them did not, guess the github linking thing is buggy. 

Patchcore has support for this as a resize option, but it is not used in patchbay. I can see it is used in edit profile in [patchwork](https://github.com/ssbc/patchwork/search?q=resize&unscoped_q=resize) and that seems to be the only place I can find. 

I'm going to merge this.

**Pull request merged**
